### ISSUE TITLE
frostlake_connector: python connector not working with v.0.1.0 db engine

### ISSUE THREAD

**Issue by aidas-truskauskas** [Frostlake-DB/frostlake-connector#1]
I am using `frostlake-connector==0.2.0` python package to connect to Frostlake server. 

It is working fine with 0.0.7 version. However, it's failing when I point to `v0.1.0` Frostlake server 

Steps to reproduce:

**Version 0.0.7**

```
./start-server-from-maven.sh 0.0.7 

Run:  frostlake_test.py


```
Result:
```
[('SNOWFLAKE', datetime.datetime(2026, 9, 14, 13, 53, 13, 37000))]
```

**Version 0.1.0**

```
./start-server-from-maven.sh 0.1.0

Run:  frostlake_test.py

```

Result:
```
 raise errors.ProgrammingError(msg=message, errno=1003, sqlstate="42000",
frostlake_connector.errors.ProgrammingError: 001003 (42000): SQL compilation error:
Object does not exist, or operation cannot be performed.
```

Scripts Used:

[frostlake_test.py](https://github.com/user-attachments/files/32196224/frostlake_test.py)

[start-server-from-maven.sh](https://github.com/user-attachments/files/32196266/start-server-from-maven.sh)

**Comment by mlorek** [comment]
Fixed in frostlake 0.2.1: plain names are now sent unquoted, so they fold to uppercase like any SQL identifier. frostlake-connector 0.2.1 requires it.
